In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
#main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# random array function
randomVals = lambda : np.random.uniform(low=0.5, high=12.4, size=(3,))

In [5]:
a2 = np.array([randomVals(),
              randomVals()])
a2


array([[12.30848994,  9.83592066, 10.38386336],
       [ 1.33802605,  6.57012292,  2.5884304 ]])

In [6]:
a3 = np.array([[randomVals(),
                randomVals(),
                randomVals()]])
a3

array([[[ 3.94052257,  2.07907795,  8.63001347],
        [ 7.34097328, 11.01339626,  3.30628876],
        [ 7.31002197,  9.38453794,  7.01841957]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(1, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [13]:
#Create a dataframe from Numpy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0         1          2
0  12.308490  9.835921  10.383863
1   1.338026  6.570123   2.588430

In [14]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [17]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 0, 7, 5, 2],
       [8, 5, 5, 6, 3],
       [3, 9, 5, 3, 8]])

In [18]:
random_array.size

15

In [19]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.68650353, 0.52508401, 0.66455169],
       [0.10363556, 0.12522535, 0.54114973],
       [0.36324172, 0.0243939 , 0.43394622],
       [0.26325913, 0.78488557, 0.68952015],
       [0.06743952, 0.65158739, 0.26364157]])

# Viewing arrays and matrices

In [20]:
np.unique(random_array)

array([0, 2, 3, 5, 6, 7, 8, 9])

# Manipulating and Comparing Arrays

In [21]:
a1

array([1, 2, 3])

In [22]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [23]:
a1 + ones 

array([2., 3., 4.])

In [24]:
a2

array([[12.30848994,  9.83592066, 10.38386336],
       [ 1.33802605,  6.57012292,  2.5884304 ]])

In [25]:
a1 * a2

array([[12.30848994, 19.67184132, 31.15159008],
       [ 1.33802605, 13.14024583,  7.76529119]])

In [26]:
a2+a1

array([[13.30848994, 11.83592066, 13.38386336],
       [ 2.33802605,  8.57012292,  5.5884304 ]])

In [27]:
a2*a1

array([[12.30848994, 19.67184132, 31.15159008],
       [ 1.33802605, 13.14024583,  7.76529119]])

In [28]:
a1.shape

(3,)

In [29]:
a2.shape

(2, 3)

## Reshaping and Transposing

In [32]:
a1 = np.random.random(2)
a1

array([0.04855802, 0.4526556 ])

In [37]:
a2 = np.random.randint(low = 1, high = 10,size=(2,3))
a2

array([[3, 4, 1],
       [6, 9, 1]])

In [39]:
a3 = np.random.randint(low = 1, high = 10, size=(2,3,3))
a3

array([[[2, 2, 3],
        [4, 7, 2],
        [6, 7, 1]],

       [[9, 1, 8],
        [2, 6, 2],
        [3, 6, 9]]])

In [42]:
a2.shape

(2, 3)

In [43]:
a3.shape

(2, 3, 3)

In [45]:
a2_reshape = a2.reshape(2,3,1)

In [46]:
a2_reshape * a3

array([[[ 6,  6,  9],
        [16, 28,  8],
        [ 6,  7,  1]],

       [[54,  6, 48],
        [18, 54, 18],
        [ 3,  6,  9]]])

In [48]:
# a2 *a3 
#ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 
# shapes are not compatible

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [49]:
a2.T

array([[3, 6],
       [4, 9],
       [1, 1]])

In [50]:
a2.T.shape # switches axis

(3, 2)

In [52]:
a3.T.shape


(3, 3, 2)

# Dot Product

In [55]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [56]:
# matDot = np.dot(mat1, mat2) # the mat1n is not equal to mat2m 
# ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [58]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# 6. Practical Example - Numpy in Action

<img src="images/panda.png"/>

In [62]:
# Turn image into Numpy Array
from matplotlib.image import imread

In [63]:
panda = imread("images/panda.png")

In [64]:
type(panda)

numpy.ndarray

In [65]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="images/car-photo.png"/>

In [66]:
car = imread("images/car-photo.png")
type(car)

numpy.ndarray

<img src="images/dog-photo.png"/>

In [69]:
dog = imread("images/dog-photo.png")
type(dog)

numpy.ndarray

In [70]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)